# Generated by Django 3.2 on 2022-04-25 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='specie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='animals.specie', verbose_name='Espécie'),
            preserve_default=False,
        ),
    ]
