# Generated by Django 3.2 on 2022-04-25 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_breed_specie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='specie',
        ),
    ]
