# Generated by Django 3.2 on 2022-04-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
