# Generated by Django 3.2 on 2022-07-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_remove_animal_specie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specie',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
    ]
