# Generated by Django 3.2 on 2022-07-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_animal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/', verbose_name='Foto'),
        ),
    ]
