# Generated by Django 3.2 on 2022-05-02 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0003_remove_animal_specie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal', verbose_name='Animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VaccineApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('lot_number', models.CharField(max_length=30, verbose_name='Lote')),
                ('manufacturing_date', models.DateField(verbose_name='Data de Fabricação')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('notify', models.BooleanField(default=False, verbose_name='Notificação')),
                ('notify_date', models.DateField(blank=True, null=True, verbose_name='Data de Notificação')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccines.vaccine', verbose_name='Vacina')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
