# Generated by Django 3.2 on 2022-05-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccineapplication',
            name='note',
        ),
        migrations.AddField(
            model_name='application',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
