# Generated by Django 3.2 on 2022-05-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20220502_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccineapplication',
            name='notify',
        ),
    ]
