# Generated by Django 3.2 on 2022-07-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_vaccineapplication_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineapplication',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Enviado'),
        ),
    ]
