# Generated by Django 3.2 on 2022-07-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
