# Generated by Django 3.2 on 2022-04-06 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20220406_0018'),
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.CreateModel(
            name='VaccineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('time_type', models.CharField(choices=[('D', 'Dia'), ('M', 'Mês'), ('A', 'Ano')], max_length=1, verbose_name='Tipo Tempo')),
                ('time_value', models.IntegerField(verbose_name='Tempo')),
                ('doses', models.IntegerField(verbose_name='Doses')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals.animal', verbose_name='Animal')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaccines.vaccine', verbose_name='Vacina')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
