# Generated by Django 3.2 on 2022-04-06 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20220406_0018'),
        ('vaccines', '0002_auto_20220406_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinesettings',
            name='animal',
        ),
        migrations.AddField(
            model_name='vaccinesettings',
            name='specie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='animals.specie', verbose_name='Especie'),
            preserve_default=False,
        ),
    ]
